object Versions {
    const val corektx  = "1.12.0"
    const val lifecycleRuntime = "2.6.2"
    const val activityCompose  = "1.7.2"
    const val composeBom = "2023.03.00"
    const val junit = "4.13.2"
    const val extJunit = "1.1.5"
    const val espresso = "3.5.1"
    const val appcompat = "1.6.1"
    const val material = "1.9.0"
    const val hiltAndroid = "2.44"
    const val hiltAndroidCompiler = "2.44"
    const val hiltCompiler = "1.0.0"
    const val navCompose = "1.0.0"
    const val retrofit = "2.9.0"
    const val okhttp = "5.0.0-alpha.2"
    const val gsonconvertor = "2.9.0"
    const val moshi = "1.13.0"
    const val moshiconvertor = "2.9.0"
    const val logginginterceptor = "4.8.1"
    const val moshiKotlin = "1.14.0"
    const val coroutineCore = "1.7.3"
    const val navigationCompose = "2.6.0"
    const val splashScreen = "1.0.1"
    const val coilCompose = "2.4.0"

}